### ISSUE TITLE
AVC Notification Issue

### ISSUE THREAD

**Issue by l-gothberg** [TedThompson/CrewPortraits#1]
This mod still throws a notification when launching if you have AVC installed:
'CrewPortraits was designed to run on KSP version 1.1.2'

You might want to look into that.

**Comment by LouisCyfer** [comment]
changing
https://github.com/TedThompson/CrewPortraits/blob/1ed62f274ad155c0bd1c62ffe930fda164a45b9b/CrewPortraits.version#L9
to
```
  "KSP_VERSION_MAX":{"MAJOR":1,"MINOR":3,"PATCH":99}
```
might solve the issue, for every KSP 1.3.* releases (assuming it will just work then aswell)

**Comment by TedThompson** [comment]
Missed this.  Just tried updating it here on GitHub.
